<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="YUL119014N07" name="Test_ProfilePage" tests="5" failures="1" timestamp="11 Feb 2016 15:01:54 GMT" time="6.638" errors="0">
  <testcase name="POS_Test_TextProfileStrength" time="0.066" classname="Test_ProfilePage"/>
  <testcase name="POS_Test_TextViewedProfile" time="2.224" classname="Test_ProfilePage">
    <failure type="java.lang.AssertionError" message="expected [Who&#039;s Viewed Your Profile] but found [Who’s Viewed Your Profile]">
      <![CDATA[java.lang.AssertionError: expected [Who's Viewed Your Profile] but found [Who’s Viewed Your Profile]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Test_ProfilePage.POS_Test_TextViewedProfile(Test_ProfilePage.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- POS_Test_TextViewedProfile -->
  <testcase name="POS_Test_ProfileName" time="0.072" classname="Test_ProfilePage"/>
  <testcase name="POS_Test_ProfilePage" time="4.183" classname="Test_ProfilePage"/>
  <testcase name="POS_Test_IsDisplayedProfileStrength" time="0.093" classname="Test_ProfilePage"/>
</testsuite> <!-- Test_ProfilePage -->
